volumes:
  prometheus-data:
  grafana-data:
services:
  prometheus:
    image: prom/prometheus
    container_name: snejinka_pet-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - snejinka-my-pet
    depends_on:
      - pushgateway
    restart: unless-stopped
  pushgateway:
    image: prom/pushgateway
    container_name: snejinka_pet-pushgateway
    networks:
      - snejinka-my-pet
    ports:
      - 9091:9091
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: snejinka_pet-grafana
    volumes:
      - ./grafana:/etc/grafana
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_USER_PASSWORD}
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - snejinka-my-pet
    depends_on:
      - prometheus
    restart: unless-stopped
  minibank-api:
    build:
      context: ./app
    container_name: snejinka_pet-minibank-api
    ports:
      - 8080:8080
    networks:
      - snejinka-my-pet
    restart: unless-stopped
    environment:
      - Jwt__Key=${JWT_KEY}
networks:
    snejinka-my-pet:
      driver: bridge
      ipam:
        config:
         - subnet: 10.5.0.0/16
